development:
  adapter: postgresql
  encoding: unicode
  database: gas_development
  pool: 5
  username: gas
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: gas_test
  pool: 5
  username: gas
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: gas_production
  pool: 5
  username: gas
  password:
